Repository AY2122S1-CS2103-T16-2/tp, pull requests merged in 2021-11, with the labels that each got.

#176 Documentation bugs for Find, UG bugs
  docs/UserGuide.md
Labels: documentation

#179 Fix UG and DG Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#180 Improve Find Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindNameSequenceDiagram.puml
  docs/diagrams/FindTutorialIdSequenceDiagram.puml
  docs/images/FindNameSequenceDiagram.png
  docs/images/FindTutorialIdSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/StatCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TutorialIdOrRoleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: bug, documentation

#187 Fixed the bug of allowing different EMAIL and NUSNET ID
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BulkTagCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug, documentation

#188 Feat/developer guide add edit bulk tag
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/BulkTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BulkTagCommandParser.java
  src/test/java/seedu/address/logic/commands/BulkTagCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/BulkTagCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: documentation

#191 Feat/updated max length for name and address
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: bug

#198 Added PPP and Updated UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/siddharth-sid.md
Labels: documentation
